service: bank-serveless
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  client:
    environment:
      DYNAMODB_USERS_TABLE:  ${ssm:dev-parameter-users-bank-bank-table-table_name}
    handler: bin/create_client
    role:  ${ssm:dev-parameter-users-bank-role-arn} 
    events:
      - httpApi:
          path: /create
          method: post